//! The category tree. Rules (see `classify.rs`) map paths to these categories.
//!
//! The tree is intentionally small and data-driven. Adding a category must not
//! require touching the scanner core.

#[derive(Debug, Clone, Copy)]
pub struct CategoryDef {
    pub id: &'static str,
    pub name: &'static str,
    pub parent: Option<&'static str>,
    pub purpose: Option<&'static str>,
    /// Extra names accepted by `diskdrift explain`.
    pub aliases: &'static [&'static str],
}

macro_rules! cat {
    ($id:literal, $name:literal, $parent:literal, $purpose:literal, [$($alias:literal),* $(,)?]) => {
        CategoryDef {
            id: $id,
            name: $name,
            parent: Some($parent),
            purpose: Some($purpose),
            aliases: &[$($alias),*],
        }
    };
}

pub static CATEGORIES: &[CategoryDef] = &[
    CategoryDef {
        id: "developer",
        name: "Developer",
        parent: None,
        purpose: Some("Data generated by development tools."),
        aliases: &["dev"],
    },
    cat!(
        "developer.xcode",
        "Xcode",
        "developer",
        "Data created by Xcode during development, builds and iOS Simulator usage.",
        ["xcode", "xcode developer data"]
    ),
    cat!(
        "developer.xcode.derived_data",
        "DerivedData",
        "developer.xcode",
        "Intermediate build products and indexes generated by Xcode.",
        ["deriveddata", "derived data"]
    ),
    cat!(
        "developer.xcode.core_simulator",
        "CoreSimulator",
        "developer.xcode",
        "Simulator runtime devices and data created by Xcode.",
        [
            "coresimulator",
            "core simulator",
            "simulator",
            "ios simulator",
            "xcode simulator"
        ]
    ),
    cat!(
        "developer.xcode.archives",
        "Archives",
        "developer.xcode",
        "App builds archived with Xcode Organizer.",
        ["archive", "xcode archives"]
    ),
    cat!(
        "developer.xcode.device_support",
        "DeviceSupport",
        "developer.xcode",
        "Debug symbols and support files for physical devices.",
        ["devicesupport", "device support", "ios devicesupport"]
    ),
    cat!(
        "developer.homebrew",
        "Homebrew",
        "developer",
        "Homebrew package manager data, downloads and installed packages.",
        ["homebrew", "brew"]
    ),
    cat!(
        "developer.docker",
        "Docker",
        "developer",
        "Docker Desktop images, containers and virtual disk data.",
        ["docker", "docker desktop"]
    ),
    cat!(
        "developer.orbstack",
        "OrbStack",
        "developer",
        "OrbStack Linux machines, containers and Docker-compatible data.",
        ["orbstack", "orb stack"]
    ),
    cat!(
        "developer.npm",
        "npm",
        "developer",
        "npm package cache.",
        ["npm", "node modules cache"]
    ),
    cat!(
        "developer.pnpm",
        "pnpm",
        "developer",
        "pnpm package store and cache.",
        ["pnpm"]
    ),
    cat!(
        "developer.yarn",
        "Yarn",
        "developer",
        "Yarn package cache and global packages.",
        ["yarn"]
    ),
    cat!(
        "developer.other",
        "Other Developer Data",
        "developer",
        "Other data stored under developer tool locations.",
        ["other developer data", "developer other"]
    ),
    CategoryDef {
        id: "ai",
        name: "AI Models",
        parent: None,
        purpose: Some("Local AI model files and caches."),
        aliases: &["ai", "models"],
    },
    cat!(
        "ai.ollama",
        "Ollama",
        "ai",
        "Downloaded local LLM models managed by Ollama.",
        ["ollama"]
    ),
    cat!(
        "ai.huggingface",
        "Hugging Face",
        "ai",
        "Models and datasets downloaded from Hugging Face.",
        ["huggingface", "hugging face", "hf"]
    ),
    cat!(
        "ai.lmstudio",
        "LM Studio",
        "ai",
        "Models and data managed by LM Studio.",
        ["lmstudio", "lm studio"]
    ),
    cat!(
        "ai.mlx",
        "MLX",
        "ai",
        "Local MLX model files and caches.",
        ["mlx", "apple mlx"]
    ),
    cat!(
        "ai.other",
        "Other Models",
        "ai",
        "Other local model data.",
        ["other models"]
    ),
    CategoryDef {
        id: "applications",
        name: "Applications",
        parent: None,
        purpose: Some("Data stored by applications."),
        aliases: &["apps", "application"],
    },
    cat!(
        "applications.app_support",
        "Application Support",
        "applications",
        "Per-application settings, databases and support data.",
        ["application support", "app support", "applicationsupport"]
    ),
    cat!(
        "applications.containers",
        "Containers",
        "applications",
        "Sandboxed application data managed by macOS.",
        ["containers", "sandbox containers"]
    ),
    cat!(
        "applications.group_containers",
        "Group Containers",
        "applications",
        "Data shared between apps of the same developer team.",
        ["group containers", "groupcontainers"]
    ),
    CategoryDef {
        id: "system",
        name: "System/User Data",
        parent: None,
        purpose: Some("System and user data that is not tied to a single app."),
        aliases: &["system", "user data", "system data"],
    },
    cat!(
        "system.caches",
        "Caches",
        "system",
        "Application cache data. Usually regenerated automatically.",
        ["caches", "cache"]
    ),
    cat!(
        "system.logs",
        "Logs",
        "system",
        "Log files written by applications and the system.",
        ["logs", "log"]
    ),
    cat!(
        "system.temporary",
        "Temporary Data",
        "system",
        "Temporary files that are expected to be short-lived.",
        ["temporary", "temp", "tmp"]
    ),
    cat!(
        "system.other",
        "Other",
        "system",
        "Scanned data that does not match a more specific category.",
        ["other", "unclassified"]
    ),
];

pub fn index_of(id: &str) -> Option<usize> {
    CATEGORIES.iter().position(|c| c.id == id)
}

pub fn def(id: &str) -> Option<&'static CategoryDef> {
    index_of(id).map(|i| &CATEGORIES[i])
}

pub fn def_by_index(idx: usize) -> &'static CategoryDef {
    &CATEGORIES[idx]
}

/// True when `idx` is `ancestor` or a descendant of `ancestor`.
pub fn is_descendant_or_self(mut idx: usize, ancestor: usize) -> bool {
    loop {
        if idx == ancestor {
            return true;
        }
        match CATEGORIES[idx].parent {
            Some(p) => match index_of(p) {
                Some(pi) => idx = pi,
                None => return false,
            },
            None => return false,
        }
    }
}

pub fn children_of(idx: usize) -> Vec<usize> {
    let id = CATEGORIES[idx].id;
    CATEGORIES
        .iter()
        .enumerate()
        .filter(|(_, c)| c.parent == Some(id))
        .map(|(i, _)| i)
        .collect()
}

pub fn depth_of(mut idx: usize) -> usize {
    let mut d = 0;
    while let Some(p) = CATEGORIES[idx].parent {
        match index_of(p) {
            Some(pi) => {
                idx = pi;
                d += 1;
            }
            None => break,
        }
    }
    d
}

/// A short label that is unique when shown in a flat list,
/// e.g. `Xcode / CoreSimulator`.
pub fn display_name(idx: usize) -> String {
    let def = &CATEGORIES[idx];
    match def.parent.and_then(def_by_id) {
        Some(parent) if depth_of(idx) >= 2 => format!("{} / {}", parent.name, def.name),
        _ => def.name.to_string(),
    }
}

fn def_by_id(id: &str) -> Option<&'static CategoryDef> {
    def(id)
}

/// Resolve a user-supplied name to a category. Used by `explain`.
pub fn resolve_token(token: &str) -> Option<usize> {
    let t = token.trim().to_lowercase();
    let t = t.trim_end_matches('.').to_string();
    if t.is_empty() {
        return None;
    }
    // Exact id, then last id component, then name, then aliases.
    if let Some(i) = index_of(&t) {
        return Some(i);
    }
    for (i, c) in CATEGORIES.iter().enumerate() {
        if c.id.rsplit('.').next() == Some(t.as_str()) {
            return Some(i);
        }
    }
    for (i, c) in CATEGORIES.iter().enumerate() {
        if c.name.to_lowercase() == t {
            return Some(i);
        }
    }
    for (i, c) in CATEGORIES.iter().enumerate() {
        if c.aliases.iter().any(|a| *a == t) {
            return Some(i);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tree_is_well_formed() {
        for (i, c) in CATEGORIES.iter().enumerate() {
            if let Some(p) = c.parent {
                assert!(index_of(p).is_some(), "unknown parent {p} for {}", c.id);
                assert!(index_of(p).unwrap() < i, "parent must be declared first");
            }
        }
    }

    #[test]
    fn descendants() {
        let xcode = index_of("developer.xcode").unwrap();
        let sim = index_of("developer.xcode.core_simulator").unwrap();
        let dev = index_of("developer").unwrap();
        assert!(is_descendant_or_self(sim, xcode));
        assert!(is_descendant_or_self(sim, dev));
        assert!(!is_descendant_or_self(xcode, sim));
        assert!(is_descendant_or_self(dev, dev));
    }

    #[test]
    fn token_resolution() {
        assert_eq!(resolve_token("xcode"), index_of("developer.xcode"));
        assert_eq!(resolve_token("Xcode"), index_of("developer.xcode"));
        assert_eq!(
            resolve_token("coresimulator"),
            index_of("developer.xcode.core_simulator")
        );
        assert_eq!(resolve_token("hugging face"), index_of("ai.huggingface"));
        assert_eq!(
            resolve_token("Application Support"),
            index_of("applications.app_support")
        );
        assert_eq!(resolve_token("nope"), None);
    }
}
