//! Storage insights: what a category is, how risky it is, and what the user
//! could review. DiskDrift never deletes anything.

use crate::core::categories;
use crate::core::fs::Accum;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Risk {
    Informational,
    Low,
    Medium,
    High,
    Unknown,
}

impl Risk {
    pub fn label(self) -> &'static str {
        match self {
            Risk::Informational => "informational",
            Risk::Low => "low",
            Risk::Medium => "medium",
            Risk::High => "high",
            Risk::Unknown => "unknown",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Recommendation {
    pub id: &'static str,
    pub title: &'static str,
    pub category_id: &'static str,
    pub allocated: u64,
    pub risk: Risk,
    pub what_is_it: &'static str,
    pub recommendation: &'static str,
    pub user_data: bool,
}

struct Rule {
    id: &'static str,
    category: &'static str,
    title: &'static str,
    risk: Risk,
    what: &'static str,
    rec: &'static str,
    user_data: bool,
}

static RULES: &[Rule] = &[
    Rule {
        id: "xcode-derived-data",
        category: "developer.xcode.derived_data",
        title: "Xcode DerivedData",
        risk: Risk::Low,
        what: "Intermediate build products and indexes generated by Xcode.",
        rec: "Review projects you no longer build; Xcode regenerates this automatically.",
        user_data: false,
    },
    Rule {
        id: "xcode-core-simulator",
        category: "developer.xcode.core_simulator",
        title: "Xcode CoreSimulator",
        risk: Risk::Low,
        what: "Simulator devices and runtime data created by Xcode.",
        rec: "Remove simulator devices you no longer use from Xcode > Devices.",
        user_data: false,
    },
    Rule {
        id: "xcode-archives",
        category: "developer.xcode.archives",
        title: "Xcode Archives",
        risk: Risk::Medium,
        what: "Archived app builds and their debug symbols.",
        rec: "Keep the archives you ship; older ones are usually safe to review.",
        user_data: false,
    },
    Rule {
        id: "xcode-device-support",
        category: "developer.xcode.device_support",
        title: "Xcode DeviceSupport",
        risk: Risk::Low,
        what: "Debug symbols copied for older iOS/watchOS versions.",
        rec: "Old OS versions can be reviewed once you no longer debug those devices.",
        user_data: false,
    },
    Rule {
        id: "homebrew",
        category: "developer.homebrew",
        title: "Homebrew",
        risk: Risk::Low,
        what: "Homebrew downloads, Cellar and Caskroom data.",
        rec: "`brew cleanup` removes old versions and downloaded artifacts.",
        user_data: false,
    },
    Rule {
        id: "package-caches",
        category: "developer.npm",
        title: "npm cache",
        risk: Risk::Informational,
        what: "Downloaded npm packages kept for faster installs.",
        rec: "Package managers can prune their own caches when you need space.",
        user_data: false,
    },
    Rule {
        id: "pnpm-store",
        category: "developer.pnpm",
        title: "pnpm store",
        risk: Risk::Informational,
        what: "Content-addressable package store used by pnpm.",
        rec: "`pnpm store prune` removes unreferenced packages.",
        user_data: false,
    },
    Rule {
        id: "yarn-cache",
        category: "developer.yarn",
        title: "Yarn cache",
        risk: Risk::Informational,
        what: "Downloaded Yarn packages.",
        rec: "`yarn cache clean` removes it when you need space.",
        user_data: false,
    },
    Rule {
        id: "docker",
        category: "developer.docker",
        title: "Docker",
        risk: Risk::High,
        what: "Docker images, containers and volumes.",
        rec: "Review in Docker Desktop first — volumes can contain databases and other data.",
        user_data: true,
    },
    Rule {
        id: "orbstack",
        category: "developer.orbstack",
        title: "OrbStack",
        risk: Risk::High,
        what: "OrbStack machines, containers and volumes.",
        rec: "Review in OrbStack first — containers and volumes can contain data.",
        user_data: true,
    },
    Rule {
        id: "ollama",
        category: "ai.ollama",
        title: "Ollama models",
        risk: Risk::Informational,
        what: "Local LLM models downloaded by Ollama.",
        rec: "Models can be re-downloaded; remove ones you no longer use with `ollama rm`.",
        user_data: false,
    },
    Rule {
        id: "huggingface",
        category: "ai.huggingface",
        title: "Hugging Face cache",
        risk: Risk::Informational,
        what: "Models and datasets downloaded from Hugging Face.",
        rec: "Re-downloadable; review if you no longer use a model.",
        user_data: false,
    },
    Rule {
        id: "lmstudio",
        category: "ai.lmstudio",
        title: "LM Studio models",
        risk: Risk::Informational,
        what: "Models managed by LM Studio.",
        rec: "Re-downloadable; review models you no longer use.",
        user_data: false,
    },
    Rule {
        id: "mlx",
        category: "ai.mlx",
        title: "MLX models",
        risk: Risk::Informational,
        what: "Local MLX model files.",
        rec: "Re-downloadable; review models you no longer use.",
        user_data: false,
    },
    Rule {
        id: "caches",
        category: "system.caches",
        title: "Application caches",
        risk: Risk::Low,
        what: "Cache data written by applications.",
        rec: "Usually regenerated automatically; DiskDrift never deletes it for you.",
        user_data: false,
    },
    Rule {
        id: "logs",
        category: "system.logs",
        title: "Logs",
        risk: Risk::Low,
        what: "Log files written by applications and the system.",
        rec: "Old logs can be archived manually if you need space.",
        user_data: false,
    },
    Rule {
        id: "app-support",
        category: "applications.app_support",
        title: "Application Support",
        risk: Risk::High,
        what: "Per-application settings, databases and support data.",
        rec: "Review in Finder; this often contains important app data.",
        user_data: true,
    },
    Rule {
        id: "containers",
        category: "applications.containers",
        title: "Containers",
        risk: Risk::High,
        what: "Sandboxed application data managed by macOS.",
        rec: "Review in Finder; sandbox containers can contain documents and settings.",
        user_data: true,
    },
    Rule {
        id: "group-containers",
        category: "applications.group_containers",
        title: "Group Containers",
        risk: Risk::High,
        what: "Data shared between apps of the same developer.",
        rec: "Review in Finder; shared containers can contain account data.",
        user_data: true,
    },
];

/// Build insights for every category that has a rule and a non-zero size.
pub fn recommendations(rolled: &[Accum]) -> Vec<Recommendation> {
    let mut out = Vec::new();
    for rule in RULES {
        let idx = match categories::index_of(rule.category) {
            Some(idx) => idx,
            None => continue,
        };
        let allocated = rolled[idx].allocated;
        if allocated == 0 {
            continue;
        }
        out.push(Recommendation {
            id: rule.id,
            title: rule.title,
            category_id: rule.category,
            allocated,
            risk: rule.risk,
            what_is_it: rule.what,
            recommendation: rule.rec,
            user_data: rule.user_data,
        });
    }
    out.sort_by_key(|rec| std::cmp::Reverse(rec.allocated));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rolled_with(entries: &[(&str, u64)]) -> Vec<Accum> {
        let mut rolled = vec![Accum::default(); categories::CATEGORIES.len()];
        for (id, bytes) in entries {
            let idx = categories::index_of(id).unwrap();
            rolled[idx].allocated = *bytes;
        }
        rolled
    }

    #[test]
    fn builds_sorted_insights() {
        let rolled = rolled_with(&[
            ("developer.xcode.derived_data", 100),
            ("developer.docker", 50),
            ("system.caches", 10),
        ]);
        let insights = recommendations(&rolled);
        assert_eq!(insights.len(), 3);
        assert_eq!(insights[0].title, "Xcode DerivedData");
        assert_eq!(insights[0].risk, Risk::Low);
        assert!(!insights[0].user_data);
        assert_eq!(insights[1].title, "Docker");
        assert_eq!(insights[1].risk, Risk::High);
        assert!(insights[1].user_data);
    }

    #[test]
    fn skips_zero_and_unknown_categories() {
        let rolled = rolled_with(&[("developer.other", 999)]);
        assert!(recommendations(&rolled).is_empty());
    }
}
